FROM openjdk:8-jdk-alpine
WORKDIR /home
COPY target/relacionamento-filmes-jar-with-dependencies.jar relacionamento-filmes-jar-with-dependencies.jar
CMD ["java", "-jar", "relacionamento-filmes-jar-with-dependencies.jar"]